apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubemage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EllistonDow/kubemage.git
    targetRevision: main
    path: gitops/clusters/kubemage-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: demo
      name: demo-magento-secrets
      jsonPointers:
        - /data
        - /stringData
    - group: ""
      kind: Secret
      namespace: bdgy
      name: bdgy-magento-secrets
      jsonPointers:
        - /data
        - /stringData
