apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EllistonDow/kubemage.git
    targetRevision: main
    path: gitops/platform/monitoring-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
