apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EllistonDow/kubemage.git
    targetRevision: main
    path: platform/monitoring
    helm:
      valueFiles:
        - ../../cluster/phase2/monitoring/kube-prometheus-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
