creation_rules:
  - path_regex: gitops/tenants/.*/secrets\.enc\.yaml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age16xulfqsvdvw9ne58gadm34dad7jlgrenw8mjyv0msjsdjg0f7v5sz3smuk
  - path_regex: gitops/platform/datastores/minio-secret\.enc\.yaml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age16xulfqsvdvw9ne58gadm34dad7jlgrenw8mjyv0msjsdjg0f7v5sz3smuk
  - path_regex: gitops/platform/messaging/.*\.enc\.yaml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age16xulfqsvdvw9ne58gadm34dad7jlgrenw8mjyv0msjsdjg0f7v5sz3smuk
