apiVersion: v1
kind: Secret
metadata:
    name: bdgy-magento-secrets
    namespace: bdgy
    labels:
        app.kubernetes.io/name: magento
        app.kubernetes.io/instance: bdgy
        app.kubernetes.io/component: secrets
stringData:
    MYSQL_USER: ENC[AES256_GCM,data:HrGNn+4tNw==,iv:7FQukBS95QTbrcVhfTcbVtO1xICqeMFl9MEG0g+jkb8=,tag:Jv2Nm19ZAIoWDueu0pROlQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:zJHaohhA16syKboV,iv:GIy6wInKU5TquV+9r2Z4RhwtVtOmKkb5SJz4vH3v6/A=,tag:KU9ZKhtcFqeMN7fRaVpxrw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:S+qnXniIRfY0UEQ4bQofRQ==,iv:/5mqDjSYHjPj0NEygAz02X4+PqRz+RenKomoakEBIOU=,tag:BCq/0Jr1fH6Dj7Z4wBiYbg==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:Z/XWnBH8Ew4NlRw=,iv:k721CiyoYz66Xqwokc0uS1sMISn0nYocZPcW/KhneCU=,tag:bx5gCvVy7Tohot/ApecWjA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:o6I+ghH/KnOX2n32FQ==,iv:pKMQlYWD+kglZHOM5UUvBi4cxNtlV3FspPQPSJphGtk=,tag:22F4XM4a5GiCmB7F0r+7vA==,type:str]
    REMOTE_STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:/3w9E3LR5qHi6K9UHw==,iv:Lx2xp1f5wBfBr9Mo3Pbebs6AyuGY97H+68OzaQgrXOk=,tag:ybTliFGRx+NTMYn9esqoCQ==,type:str]
    REMOTE_STORAGE_SECRET_KEY: ENC[AES256_GCM,data:ezfxrwniPxgXhWF6s1KA+/TG2Ag=,iv:VAsyaMaTyh/vxLLrwXfkcaBLSkRq5S6SUsPyPMOFlSw=,tag:G0/blIbnOKXidgnHNBbNdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16xulfqsvdvw9ne58gadm34dad7jlgrenw8mjyv0msjsdjg0f7v5sz3smuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY292bFZUNUl1QnhnVU9Y
            MG5idE1WQmxQNXFjUEQwL2t0VmlBNjFwNWs0CmxSeUFDZ0Y0QWkycElFa1FNdTZE
            MTBydDZFenlOb1dHaWl1WElZZHp1UzAKLS0tIDFDWUJQV3FzNFFXMXFxNmVmUllL
            Tm9VTXg0clA4SDd4NEYzai81cjc5eW8KJMbaCNDVuCHSf5cl45GUxz07iHRqvTb8
            pHZ5g9/rS++H1HKDjT2Mhkf4twh9Xisr6F0F4PWt0DITzUao3ibbXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T09:06:59Z"
    mac: ENC[AES256_GCM,data:88wHe68ZCG7FmnptuaDXVLpSXfYp4ShcegX96PoLKgMgEEYHG9Hkb9Wbi+qr+XAP3IwSVn2h5XDQZXvMMG2hSspzQ5mk8CS1m3HLVIRz5Ck1R1BPfmYRHpL/C1QHwxt1HtG+5T+7NLyXGSYEixWRuxf4YP/NuY1CTrVJoACV+CY=,iv:czSdRgwYotV2JtrHK15mFwauSsakAb4wBE9EDvVEZWc=,tag:UvdxwSnMrzAnvGdJ9OFdaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
