apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-metrics
  namespace: messaging
  labels:
    app: rabbitmq
    kubemage.io/component: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: metrics
      port: 15692
      targetPort: 15692
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-metrics
  namespace: monitoring
  labels:
    kubemage.io/component: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      kubemage.io/component: rabbitmq
  namespaceSelector:
    matchNames:
      - messaging
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
