apiVersion: v1
kind: Secret
metadata:
    name: demo-magento-secrets
    namespace: demo
    labels:
        app.kubernetes.io/name: magento
        app.kubernetes.io/instance: kubemage
        app.kubernetes.io/component: secrets
stringData:
    MYSQL_USER: ENC[AES256_GCM,data:+d5/Wqxz8Q==,iv:3zjHU3s5bT+DjU5K5MOD5iFPKuHh1RIdLjBNHaAiAwg=,tag:pTOaAt3BNNdMyaTPzQjxTw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:A4J6hnh9j7UTAKPT,iv:yO2BkyNa7ppBZqSYZeuaYsHRjLqq2BanDWbo9JZm2CU=,tag:U2NvastI54SB6rIOTPJrKg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:A8HmVCrtZswy3O/xWEOwyQ==,iv:Z0/L+i87Fq56tmvEQW2GGeyaIK05Tk9E3xYNoQBSvlA=,tag:v/Idw1EbChq9Z4GsFsbWkQ==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:SUCtU8/jDQz/Xdg=,iv:frL9P+53W5KkQJgoAvo2tldw+3luUA4l9xcQBBupd04=,tag:mlGaRQrb/GkjoI393TciMQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:0etCaCW7OgUhh8qI+Q==,iv:Z3InGG2ZwH1KSYyUckEHIXgFd0fVU5I8TbskIyKV12M=,tag:6mC2z3rR7NBCQcvro9EGHw==,type:str]
    REMOTE_STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:1sg96LsgZc0BszbLjA==,iv:GefuU8Q410Z3N7tbGjc0IZOJfD3emSN4iggHF6Mq438=,tag:rFgMMlRpYJaTpPwUg+oxlA==,type:str]
    REMOTE_STORAGE_SECRET_KEY: ENC[AES256_GCM,data:A+AjBTbcNluxa0jNwuPgqM/f/pc=,iv:Y7fuQ6sbl4F4km3faogfoHyPZPS+w36r5VScwTyvGCU=,tag:B2BI07C39P5CRVI802qWnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16xulfqsvdvw9ne58gadm34dad7jlgrenw8mjyv0msjsdjg0f7v5sz3smuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudmVRcDYxWDhiOTZ2M3RS
            dVlYVHIxcklpM2k2cUZycm41RHU3bmhpVUFrClRKbWNhc053cktKcnAwMDk2a3k4
            REI5OStrR2dETUdhRmNlQVAyZ0JybDQKLS0tIG81cC9UK0twRFh3cUtGRGdBOEgw
            YmJuTmpsdTcrWVpPSzdTaHBtZks0ZE0KhPygOcvtJSOlzPoC7S0ti4xPOT/97PZz
            DPeqD0V4u/6YWQmOQu+6m5vp7rIHB5zFhgjH8cq8lCylq65WgjsPEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T09:05:51Z"
    mac: ENC[AES256_GCM,data:L30O3Ern5Hyc4mxXUtn8fDTZEiqTqGNTHMsA1XsBSUNt1kG7pQTtI5q3FiVFrcxNrfJrny5v0qr8F28ing9DVbM1l5YUzJJu9p908YocAFhNKGHJVE+BY2sF4j4xH2Y26xQfJAtxiiUBjuvdEi+hcqW05WGQwQyKD+1oqj1IYqE=,iv:yMtD04sYumMf5lpKY3+TRS4tBj3zmpKaitdGzMCX9pY=,tag:A7+hTrwfD+gSBrRQEEuE4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
