apiVersion: v1
kind: Secret
metadata:
  name: varnish-vcl
  namespace: edge
stringData:
  magento.vcl: |
    vcl 4.1;
    import std;
    backend default {
      .host = "magento-web.edge.svc";
      .port = "8080";
    }
    sub vcl_recv {
      if (req.method == "PRI") {
        return (synth(405));
      }
      if (req.url ~ "(?i)wp-login.php" ) {
        return (synth(403, "Forbidden"));
      }
    }
    sub vcl_backend_response {
      if (beresp.http.cache-control ~ "private") {
        set beresp.ttl = 0s;
      }
    }
