apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        existingSecret: minio-root-credentials
        mode: distributed
        replicas: 4
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        persistence:
          enabled: true
          storageClass: local-path
          size: 200Gi
        buckets:
          - name: demo-media
          - name: bdgy-media
          - name: shared-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: object-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
