apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: search
spec:
  clusterIP: None
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9210
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: search
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.19.0
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms4g -Xmx4g"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-auth
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-http
  namespace: search
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9210
      targetPort: 9200
