apiVersion: batch/v1
kind: CronJob
metadata:
  name: shared-backup-dropbox
  namespace: ops
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dropbox-sync
              image: alpine:3.20
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  JOB_NAME="shared-backup-dropbox"
                  log() { echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $*"; }
                  notify() {
                    if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
                      return
                    fi
                    if ! command -v curl >/dev/null 2>&1; then
                      echo "[${JOB_NAME}] curl 不存在，跳过 Telegram 通知" >&2
                      return
                    fi
                    local text="$1"
                    curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                      -d chat_id="${TELEGRAM_CHAT_ID}" \
                      -d text="$text" >/dev/null || true
                  }
                  trap 'notify "❌ [${JOB_NAME}] Dropbox 同步失败 (exit $?) at $(date -u +%F_%T)"; exit 1' ERR
                  apk add --no-cache rsync >/dev/null
                  TARGET="/dropbox"
                  mkdir -p "$TARGET"
                  log "rsync /backups → $TARGET"
                  rsync -av --delete /backups/ "$TARGET/"
                  chown -R 1000:1000 "$TARGET"
                  log "Dropbox 同步完成"
                  notify "✅ [${JOB_NAME}] 完成 at $(date -u +%F_%T)"
              envFrom:
                - secretRef:
                    name: shared-backup-secrets
              volumeMounts:
                - name: backup
                  mountPath: /backups
                  readOnly: true
                - name: dropbox
                  mountPath: /dropbox
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: shared-backup
            - name: dropbox
              hostPath:
                path: /home/doge/Dropbox/kubemage/shared-backup
                type: DirectoryOrCreate
