apiVersion: batch/v1
kind: CronJob
metadata:
  name: shared-backup
  namespace: ops
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: shared-backup
          restartPolicy: Never
          containers:
            - name: backup
              image: dtzar/helm-kubectl:3.13.3
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  /opt/scripts/shared-backup.sh
              env:
                - name: BACKUP_ROOT
                  value: /backups
                - name: SNAPSHOT_ROOT
                  value: /snapshots
                - name: SHARED_BACKEND
                  value: k8s
                - name: PERCONA_NAMESPACE
                  value: databases
                - name: OPENSEARCH_NAMESPACE
                  value: search
                - name: OPENSEARCH_SELECTOR
                  value: app=opensearch
                - name: OPENSEARCH_K8S_CONTAINER
                  value: opensearch
                - name: PERCONA_SELECTOR
                  value: app.kubernetes.io/instance=percona-cluster-pxc-d
                - name: PERCONA_K8S_CONTAINER
                  value: pxc
                - name: OPENSEARCH_ENDPOINT
                  value: http://opensearch.search.svc.cluster.local:9200
                - name: PERCONA_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: shared-backup-secrets
                      key: PERCONA_ROOT_PASSWORD
              volumeMounts:
                - name: script
                  mountPath: /opt/scripts
                  readOnly: true
                - name: backup
                  mountPath: /backups
                - name: snapshots
                  mountPath: /snapshots
          volumes:
            - name: script
              configMap:
                name: shared-backup-script
                defaultMode: 0755
            - name: backup
              persistentVolumeClaim:
                claimName: shared-backup
            - name: snapshots
              persistentVolumeClaim:
                claimName: shared-opensearch-snapshots
