apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.kubemage.example.com
      path: kubemage
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: kubemage-eso
