apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/kubemage-gitops.git
    targetRevision: main
    path: platform/security
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
